algorithms:
  iforest:
    parameters:
      treesCount: 100
      subsampleSize: 256
      trainSize: 30000
    gridsearch:
      measure: pr
      parameters:
        treesCount:
          - 50
          - 100
          - 200
          - 300
          - 400
          - 500
        subsampleSize:
          - 50
          - 100
          - 200
          - 256
          - 300
          - 400
          - 500

  lof-bkaluza:
    parameters:
      knn: 15
      trainSize: 400
    gridsearch:
      measure: pr
      parameters:
        knn:
          - 15
          - 20
          - 30
          - 40
          - 50
          - 80
          - 100

  mcod:
    parameters:
      maxDistance: 13.0
      minNeighborCount: 150
      classifierWindowSize: 10000000
      classifierSlide: 10000000
      allowDuplicates: false
    gridsearch:
      measure: pr
      parameters:
        maxDistance:
          - 0.1
          - 0.2
          - 0.5
          - 1.0
          - 2.0
          - 3.0
          - 6.0
          - 8.0
          - 10.0
          - 15.0
          - 30.0
          - 50.0
          - 80.0
          - 100.0
          - 150.0
          - 200.0
          - 400.0
          - 500.0
          - 800.0
          - 1000.0
          - 3000.0
          - 5000.0
          - 10000.0
        minNeighborCount:
          - 3
          - 5
          - 10
          - 15
          - 20
          - 30
          - 50
          - 80
          - 120
          - 150
          - 250
          - 300
          - 400
          - 500
          - 1000
          - 2000

  fastmcd:
    parameters:
      alpha: 0.9
      stoppingDelta: 0.00001
      trainSize: 4000

  percentile:
    parameters:
      cutoff: 0.5
      includeHi: true
      includeLo: true

  mad:
    parameters:
      trainSize: 4000

  random:
    parameters:
      binary: false
