uri: csv://Abalone/abalone-sub-onehot.csv
metricColumns:
  - length
  - diameter
  - height
  - whole_weight
  - shucked_weight
  - viscera_weight
  - shell_weight
  - sex_f
  - sex_i
  - sex_m
labelColumn: is_anomaly