uri: csv://Covtype/covtype-sub.csv
metricColumns:
  - elevation
  - aspect
  - slope
  - horizontal_distance_to_hydrology
  - vertical_distance_to_hydrology
  - horizontal_distance_to_roadways
  - hillshade_9am
  - hillshade_noon
  - hillshade_3pm
  - horizontal_distance_to_fire_points
  - wilderness_area1
  - wilderness_area2
  - wilderness_area3
  - wilderness_area4
  - soil_type1
  - soil_type2
  - soil_type3
  - soil_type4
  - soil_type5
  - soil_type6
  - soil_type7
  - soil_type8
  - soil_type9
  - soil_type10
  - soil_type11
  - soil_type12
  - soil_type13
  - soil_type14
  - soil_type15
  - soil_type16
  - soil_type17
  - soil_type18
  - soil_type19
  - soil_type20
  - soil_type21
  - soil_type22
  - soil_type23
  - soil_type24
  - soil_type25
  - soil_type26
  - soil_type27
  - soil_type28
  - soil_type29
  - soil_type30
  - soil_type31
  - soil_type32
  - soil_type33
  - soil_type34
  - soil_type35
  - soil_type36
  - soil_type37
  - soil_type38
  - soil_type39
  - soil_type40
labelColumn: is_anomaly