uri: csv://Thyroid/thyroid-ann-test-sub.csv
metricColumns:
  - d1
  - b1
  - b2
  - b3
  - b4
  - b5
  - b6
  - b7
  - b8
  - b9
  - b10
  - b11
  - b12
  - b13
  - b14
  - b15
  - d2
  - d3
  - d4
  - d5
  - d6
labelColumn: is_anomaly