uri: csv://Wine/winequality-white.csv
metricColumns:
  - fixed_acidity
  - volatile_acidity
  - citric_acid
  - residual_sugar
  - chlorides
  - free_sulfur_dioxide
  - total_sulfur_dioxide
  - density
  - ph
  - sulphates
  - alcohol
labelColumn: is_anomaly